version: "3"
services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    platform: linux/arm64
    environment:
      POSTGRES_DB: $PG_DATABASE
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
    ports:
      - 5432:5432
    expose:
      - "5432"
    volumes:
      - cron:/var/lib/postgres

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "9090:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=cron
    depends_on:
      - postgres

  # cron-be:
  #   image: cron-be:prod
  #   restart: unless-stopped
  #   platform: linux/arm64
  #   env_file:
  #     - .env
  #   environment:
  #     PG_URL: "postgres:5432"
  #   ports:
  #     - "8080:8080"
  #   expose:
  #     - "8080"

volumes:
  cron:
