name: cron
services:
  postgres:
    container_name: cron-postgres
    image: postgres:16-alpine
    restart: unless-stopped
    platform: linux/arm64
    environment:
      POSTGRES_DB: $PG_DATABASE
      POSTGRES_USER: $PG_USER
      POSTGRES_PASSWORD: $PG_PASSWORD
    ports:
      - 5432:5432
    expose:
      - "5432"
    volumes:
      - postgres:/var/lib/postgres

  adminer:
    container_name: cron-adminer
    image: adminer
    restart: unless-stopped
    ports:
      - "9090:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=postgres
      - ADMINER_DESIGN=dracula
    depends_on:
      - postgres

  # cron-be:
  #   container_name: cron_be
  #   image: cron-be:go
  #   restart: unless-stopped
  #   platform: linux/arm64
  #   environment:
  #     PG_URL: "postgres:5432"
  #   ports:
  #     - "8080:8080"
  #   expose:
  #     - "8080"

volumes:
  postgres:
