version: "3"
services:
  mysql:
    image: mysql:8.3.0
    restart: unless-stopped
    platform: linux/arm64
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "cron"
      MYSQL_USER: "cron"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - cron:/var/lib/mysql

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - "9090:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=cron
    depends_on:
      - mysql

volumes:
  cron:
