basePath: /api/v1
definitions:
  auth.AuthenticateResponse:
    properties:
      access_token:
        type: string
      expires_at:
        type: integer
      expires_in:
        type: integer
      refresh_token:
        type: string
      token_type:
        type: string
      user:
        $ref: '#/definitions/models.User'
    type: object
  auth.RefreshTokenResponse:
    properties:
      access_token:
        type: string
      expires_at:
        type: integer
      expires_in:
        type: integer
      refresh_token:
        type: string
      token_type:
        type: string
    type: object
  models.Event:
    properties:
      created_at:
        type: string
      end_time:
        type: string
      id:
        type: string
      repeated:
        type: string
      start_time:
        type: string
      timezone:
        type: string
      title:
        type: string
      user_id:
        type: string
    type: object
  models.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      id:
        type: string
      name:
        type: string
      password:
        type: string
    type: object
  response.Error:
    properties:
      code:
        type: integer
      error: {}
      status:
        type: string
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      status:
        type: string
    type: object
info:
  contact:
    email: ushiradineth@gmail.com
    name: Ushira Dineth
    url: https://ushira.com
  description: Backend for Cron calendar management app.
  title: Cron
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Authenticate User with the parameters sent with the request
      parameters:
      - in: query
        name: email
        required: true
        type: string
      - in: query
        maxLength: 20
        minLength: 8
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/auth.AuthenticateResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Authenticate User
      tags:
      - Auth
  /auth/refresh:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Refresh Access Token with the parameters sent with the request
        based on the request based on the JWT
      parameters:
      - in: query
        name: refresh_token
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/auth.RefreshTokenResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - BearerAuth: []
      summary: Refresh Access Token
      tags:
      - Auth
  /auth/reset-password:
    put:
      consumes:
      - application/x-www-form-urlencoded
      description: Update authenticated user's Password with the parameters sent with
        the request based on the JWT
      parameters:
      - in: query
        maxLength: 20
        minLength: 8
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - BearerAuth: []
      summary: Update User Password
      tags:
      - Auth
  /events:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: Get authenticated user's event based on the JWT sent with the request
      parameters:
      - in: query
        name: end_day
        required: true
        type: string
      - in: query
        name: start_day
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/models.Event'
                  type: array
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - BearerAuth: []
      summary: Get User Events
      tags:
      - Event
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Create Event based on the parameters sent with the request
      parameters:
      - in: query
        name: end_time
        required: true
        type: string
      - enum:
        - never
        - daily
        - weekly
        - monthly
        - yearly
        in: query
        name: repeated
        required: true
        type: string
      - in: query
        name: start_time
        required: true
        type: string
      - in: query
        name: timezone
        required: true
        type: string
      - in: query
        name: title
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/models.Event'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - BearerAuth: []
      summary: Create Event
      tags:
      - Event
  /events/{event_id}:
    delete:
      consumes:
      - application/x-www-form-urlencoded
      description: Delete Event based on the parameters sent with the request
      parameters:
      - in: path
        name: event_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - BearerAuth: []
      summary: Delete Event
      tags:
      - Event
    get:
      description: Get authenticated user's event based on the JWT and event ID sent
        with the request
      parameters:
      - in: path
        name: event_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/models.Event'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - BearerAuth: []
      summary: Get Event by ID
      tags:
      - Event
    put:
      consumes:
      - application/x-www-form-urlencoded
      description: Update Event based on the parameters sent with the request
      parameters:
      - in: path
        name: event_id
        required: true
        type: string
      - in: query
        name: end_time
        required: true
        type: string
      - enum:
        - never
        - daily
        - weekly
        - monthly
        - yearly
        in: query
        name: repeated
        required: true
        type: string
      - in: query
        name: start_time
        required: true
        type: string
      - in: query
        name: timezone
        required: true
        type: string
      - in: query
        name: title
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/models.Event'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - BearerAuth: []
      summary: Update Event
      tags:
      - Event
  /users:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: Create User with the parameters sent with the request
      parameters:
      - in: query
        name: email
        required: true
        type: string
      - in: query
        name: name
        required: true
        type: string
      - in: query
        maxLength: 20
        minLength: 8
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/models.User'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      summary: Create User
      tags:
      - User
  /users/{user_id}:
    delete:
      consumes:
      - application/x-www-form-urlencoded
      description: Delete authenticated User based on the JWT
      parameters:
      - in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: string
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - BearerAuth: []
      summary: Delete User
      tags:
      - User
    get:
      description: Get authenticated user based on the JWT sent with the request
      parameters:
      - in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/models.User'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - BearerAuth: []
      summary: Get User
      tags:
      - User
    put:
      consumes:
      - application/x-www-form-urlencoded
      description: Update authenticated User with the parameters sent with the request
        based on the JWT
      parameters:
      - in: path
        name: user_id
        required: true
        type: string
      - in: query
        name: email
        required: true
        type: string
      - in: query
        name: name
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/models.User'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.Error'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/response.Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/response.Error'
      security:
      - BearerAuth: []
      summary: Update User
      tags:
      - User
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
